### ISSUE TITLE
python manage.py migratecomment [app_label] 

### ISSUE THREAD

**Issue by yagche** [starryrbs/django-comment-migrate#14]
非常有用的库，非常感谢！

顺便提一个小问题：
python manage.py migratecomment [app_label]
加上app_label后无法识别会报错：
(venv) candy@ubuntu-VirtualBox:/opt/soft/xxxx-procurement/xxxx_procurement$ ./manage.py migratecomment procurement  
usage: manage.py migratecomment [-h] [--database DATABASE]
                                [--app_label [APP_LABEL [APP_LABEL ...]]]
                                [--version] [-v {0,1,2,3}]
                                [--settings SETTINGS]
                                [--pythonpath PYTHONPATH] [--traceback]
                                [--no-color] [--force-color] [--skip-checks]
manage.py migratecomment: error: unrecognized arguments: procurement

**Comment by starryrbs** [comment]
非常感谢你的使用,目前还不支持只迁移单个app,后面会提交pr来支持此功能

**Comment by starryrbs** [comment]
请更新django-comment-migrate,已经支持此功能了。
