### ISSUE TITLE
字段注释可以用，表注释怎么添加呢？

### ISSUE THREAD

**Issue by xiayin1992728** [starryrbs/django-comment-migrate#26]
![image](https://user-images.githubusercontent.com/29964737/124866347-dabd9480-dfee-11eb-8e9c-c0970c749558.png)

**Comment by starryrbs** [comment]
感谢你提交的issue！
暂时不支持给表添加注释，但是这是一个很好的建议，后面会实现该功能，也欢迎你提交pull request！

**Comment by xiayin1992728** [comment]
> 感谢你提交的issue！
> 暂时不支持给表添加注释，但是这是一个很好的建议，后面会实现该功能，也欢迎你提交pull request！

很不错的插件，不过不能直接获取  verbose_name 当成注释，只能使用 help_text,

**Comment by starryrbs** [comment]
是的，这个可以做成可配置的，但是目前不支持。

**Comment by zwd759648544** [comment]
很很不错的插件，点个👍

很期待能支持表加注释这个功能

**Comment by starryrbs** [comment]
哈哈，感谢你的使用，这个功能会尽快实现的。

**Comment by zwd759648544** [comment]
> 哈哈，感谢你的使用，这个功能会尽快实现的。

[强][强][强]

**Comment by zwd759648544** [comment]
> 哈哈，感谢你的使用，这个功能会尽快实现的。

👍  👍  👍

**Comment by starryrbs** [comment]
> > 感谢你提交的issue！
> > 暂时不支持给表添加注释，但是这是一个很好的建议，后面会实现该功能，也欢迎你提交pull request！
> 
> 很不错的插件，不过不能直接获取 verbose_name 当成注释，只能使用 help_text,

@xiayin1992728  现在支持自定义注释的字段了，使用如下：

在settings.py

```
DCM_COMMENT_KEY='verbose_name'
```

**Comment by starryrbs** [comment]
现在已经支持添加表注释了，默认是 model meta的 verbose_name字段 
[pull request](https://github.com/starryrbs/django-comment-migrate/pull/33)
@zwd759648544 @xiayin1992728
