### ISSUE TITLE
不支持我自定义的数据库

### ISSUE THREAD

**Issue by juzj** [starryrbs/django-comment-migrate#38]
![image](https://user-images.githubusercontent.com/36066382/141936968-6a7716a8-e205-4260-9826-8419290334fc.png)

**Comment by starryrbs** [comment]
可以自定义配置，参考这个 https://github.com/starryrbs/django-comment-migrate/blob/develop/README-zh_CN.rst#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE

**Comment by juzj** [comment]
好的 感谢

**Comment by starryrbs** [comment]
不客气，可以的话帮忙点个赞

**Comment by juzj** [comment]
好的

**Comment by juzj** [comment]
![image](https://user-images.githubusercontent.com/36066382/141938215-5f8ec216-e72e-4645-90f0-d555bf033329.png)
![image](https://user-images.githubusercontent.com/36066382/141938242-cbec9c18-697d-4ab0-a2da-77bb769ff1ef.png)
我这样使用对吗？
报错：django.db.utils.OperationalError: (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")

**Comment by starryrbs** [comment]
```
DCM_BACKEND={
   "utils.mysql_backends": "django_comment_migrate.backends.mysql.CommentMigration"
}
```
应该是这样

**Comment by juzj** [comment]
![image](https://user-images.githubusercontent.com/36066382/141939311-c1bef88b-4190-4ab3-96aa-742ff438fa6e.png)
如果我要有多个model 我就要写多个   "utils.mysql_backends": "django_comment_migrate.backends.mysql.CommentMigration"
 吗

**Comment by juzj** [comment]
不支持这样使用
![image](https://user-images.githubusercontent.com/36066382/141939573-835070f8-6d11-4063-b997-1f26fd25f416.png)

**Comment by starryrbs** [comment]
这是写到django的settings文件里面的

**Comment by juzj** [comment]
![image](https://user-images.githubusercontent.com/36066382/141939821-b01909d7-d5ff-4b32-b785-a43ab6b1df1a.png)
是在settings文件里面的

**Comment by starryrbs** [comment]
你断点打到这里看看 https://github.com/starryrbs/django-comment-migrate/blob/c78bb5acfffecbcc11fae95ea09c1a6c321bfa03/django_comment_migrate/db_comments.py#L24

**Comment by juzj** [comment]
![image](https://user-images.githubusercontent.com/36066382/141940565-f7fe16ae-20dc-4417-b7f5-47fde39b35a7.png)
和settings配置的一样

**Comment by starryrbs** [comment]
改成这样试试
```
DCM_BACKEND={
   "mysql_backends": "django_comment_migrate.backends.mysql.CommentMigration"
}
DCM_COMMENT_KEY="help_text"

```

**Comment by juzj** [comment]
可以正常执行migrate 执行完成后数据库并没有生成对应的注释 

```settings配置
INSTALLED_APPS = [
django_comment_migrate
]

DCM_BACKEND = {
    "mysql_backends": "django_comment_migrate.backends.mysql.CommentMigration"
}
DCM_COMMENT_KEY = "help_text"
```

model
![image](https://user-images.githubusercontent.com/36066382/141946334-860f86cd-c8cd-4102-8589-d04c79188490.png)

表结构
![image](https://user-images.githubusercontent.com/36066382/141946283-7226f4d0-b4e5-4007-b59f-bf55492171a2.png)

**Comment by starryrbs** [comment]
断点打到这一行，debug看一下 https://github.com/starryrbs/django-comment-migrate/blob/c78bb5acfffecbcc11fae95ea09c1a6c321bfa03/django_comment_migrate/backends/mysql.py#L38

**Comment by juzj** [comment]
走不到这一步
![image](https://user-images.githubusercontent.com/36066382/141947177-2238a0b4-24a7-496f-81a6-65ca2f1bf895.png)

**Comment by starryrbs** [comment]
用这个命令重新生成下字段注释
```
python manage.py migratecomment
```

**Comment by juzj** [comment]
可以了 感谢

**Comment by starryrbs** [comment]
不客气
