### ISSUE TITLE
是否支持支持django3.2

### ISSUE THREAD

**Issue by fine-ypc** [starryrbs/django-comment-migrate#42]
您好，我遇到了一个问题。
我装了包了，但是在 **INSTALLED_APPS** 中填入时 提示如下
![image](https://user-images.githubusercontent.com/48499756/147064225-601350bd-46f1-4a64-9d43-c21ead8b843f.png)
![image](https://user-images.githubusercontent.com/48499756/147064344-4b6d1322-c35b-4b1d-886d-6aec2042356d.png)

**Comment by starryrbs** [comment]
1. 检查有没有 pip install
2. 检查`django_comment_migrate` 后面有没有少逗号

**Comment by fine-ypc** [comment]
有检查了，我也有点迷😶
![image](https://user-images.githubusercontent.com/48499756/147065154-ea4d8a6f-64a1-4d28-88c5-d70491210d19.png)
![image](https://user-images.githubusercontent.com/48499756/147065270-38ec28e8-1f59-4e84-b154-5ccef00031a3.png)

**Comment by starryrbs** [comment]
虚拟环境设置对吗？

**Comment by fine-ypc** [comment]
= = 重开了一下pycharm 等它索引完就可以了。。 提了这么个issue，好呆😳。感谢感谢，已经用起来了。

**Comment by starryrbs** [comment]
嗯呢
