### ISSUE TITLE
当存在继承的情况，会出现报错。使用 postgresql 报错：django.db.utils.ProgrammingError: column

### ISSUE THREAD

**Issue by baiyea** [starryrbs/django-comment-migrate#52]
当存在继承的情况，会出现报错。使用 postgresql 报错：django.db.utils.ProgrammingError: column

![image](https://user-images.githubusercontent.com/8907916/203289865-71ca5ee3-2f01-43e3-be2b-16f9f1853650.png)

我的表结构
![image](https://user-images.githubusercontent.com/8907916/203290108-fd1e8e46-f0ca-40d5-81df-e458e5cc10e8.png)

我继承的表结构
![image](https://user-images.githubusercontent.com/8907916/203290119-8288fe5e-dbd3-41ee-8541-826b2fc4ab98.png)

**Comment by starryrbs** [comment]
可以提一个pr呢

**Comment by baiyea** [comment]
> 可以提一个pr呢

好的，刚提了

**Comment by baiyea** [comment]
> > 可以提一个pr呢
> 
> 好的，刚提了

还不大会玩github，我原来按照说明文档，我以为我提了呢。。

**Comment by starryrbs** [comment]
> > > 可以提一个pr呢
> > 
> > 
> > 好的，刚提了
> 
> 还不大会玩github，我原来按照说明文档，我以为我提了呢。。

你没有提pr啊，是提到这个仓库里，我发布一个版本

**Comment by baiyea** [comment]
> > > > 可以提一个pr呢
> > > 
> > > 
> > > 好的，刚提了
> > 
> > 
> > 还不大会玩github，我原来按照说明文档，我以为我提了呢。。
> 
> 你没有提pr啊，是提到这个仓库里，我发布一个版本

哈哈，还是不会搞，再看一下，可以了不

**Comment by starryrbs** [comment]
可以了，发布了0.1.7 版本 https://pypi.org/project/django-comment-migrate/#history
